### ISSUE TITLE
Build Failure:  Unknown plugin "mjsx" 

### ISSUE THREAD

**Issue by fatpixel** [gabriel-hook/contest-of-champions#6]
Every time I run `gulp build`, I receive the following error:

``` bash
$ gulp build
[21:36:26] Requiring external module babel-core/register
/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, 
                ^
ReferenceError: Unknown plugin "mjsx" specified in "/Users/fatpixel/.code/git/contest-of-champions/.babelrc" at 0, attempted to resolve relative to "/Users/fatpixel/.code/git/contest-of-champions"
    at /Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at compile (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/node_modules/babel-register/lib/node.js:87:26)
    at loader (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/node_modules/babel-register/lib/node.js:127:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fatpixel/.code/git/contest-of-champions/node_modules/babel-core/node_modules/babel-register/lib/node.js:137:7)
```

**Comment by gabriel-hook** [comment]
I put directions on the Readme.md. The mjsx plugins I'm using aren't 100% production so you need to update a couple libraries after doing your npm install. I have instructions on which ones and how.

**Comment by gabriel-hook** [comment]
Please let me know if this helps you and I'll close it,  I'll probably redo the setup tomorrow so you don't need to manually install like this

**Comment by fatpixel** [comment]
@gabriel-hook that totally helps!

Thanks!

**Comment by gabriel-hook** [comment]
As a side note, I made sure you don't have to do some deep node_modules installs to get the server to work.
